// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtzwqhcjuecojmmdyyiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0endxaGNqdWVjb2ptbWR5eWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzQwMDMsImV4cCI6MjA2NjYxMDAwM30.pYxDEK6-TVDq-fMlk4ujaExq84dBX9i28F791Ldw6mQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);